### PR TITLE
Add nbs for next lessons: first GP, how to set priors

### PR DESCRIPTION
**Pull request by bwengals**

### CODE REVIEW

**Comment by canyon289** [comment]
Here's some parrial comments, Ill leave more tomorrow. TLDR though this is great!

# Notes on GP Section
This is fantastic
Lots of graphs, lots of codes, the explanations are great.
You go from intuition to code to math
Hospital example is great
Showing the "bare bones" gp in ccode is good

## Comments
* I can handle the reparameterization explanation, largely telling folks to really understand it you'll need to take the practical MCMC course, or gain an equivalent understanding

## Questions/Ideas
1. After explaining priors in Section 30, can we inculde a section 35 that shows how different random samples are ranked with likelihoods? We could do this just with MVNs, basically have MVN_1,  MVN_2, MVN_3, where MVN_1 ~= MVN_2 and MVN3 ~!= MVN1.
Then we can show how just like "regular" bayes theorem, all were doing is assessing "if we see this sample from MVN2 or MVN2, how likely was it it came from MVN1"
    * I suggest this for two reasons. First is reconnects this to basic bayes theorem, and likelihood in general. Secondly. it adds an "easy" section before we dive into a harder sections 
2. The split between MVN and GP is great. To better highlight this at the start of section 30 we can copy the definition that that's mentioned in section 60, and then repeat it again in section 60. 

## Priors section
* No specific questions. For rest of cousre then woulld we
  * Lesson Kernels
  * Rexplain mauna loa
  * Practial examples and downsides? That GPs can have issues regularly and there's new advances like HSGP to deal with stuff like this?

**Comment by bwengals** [comment]
Thanks for the comments Ravin, much appreciated.  Sounds like were moving in the right direction again.

> I can handle the reparameterization explanation, largely telling folks to really understand it you'll need to take the practical MCMC course, or gain an equivalent understanding

That sounds good, I'd imagine you'd cover this in the MCMC course and advanced reg too.  I can simplify the explanation here then. 

> After explaining priors in Section 30, can we inculde a section 35 that shows how different random samples are ranked with likelihoods? We could do this just with MVNs, basically have MVN_1, MVN_2, MVN_3, where MVN_1 ~= MVN_2 and MVN3 ~!= MVN1.
Then we can show how just like "regular" bayes theorem, all were doing is assessing "if we see this sample from MVN2 or MVN2, how likely was it it came from MVN1"
I suggest this for two reasons. First is reconnects this to basic bayes theorem, and likelihood in general. Secondly. it adds an "easy" section before we dive into a harder sections

I guess I'm a little confused by what you're after here.  The likelihood is defined as p(data | theta) right, and there's no observed data at this point.  So Bayes theorem isn't involved yet -- it's just samples from the GP prior.  What you're proposing sounds maybe like a model selection problem?  Which I think is too advanced for this stage.  Please fill me in though if I'm not following ofc.  In the following hospital example the likelihood is Poisson and that's the first time data is introduced.  

I really want to emphasize in this lesson that GPs have absolutely nothing to do with the likelihood, because this was a source of a lot of confusion for me and I think others.  I'm planning on having a later section on marginalization.  This only apples for the specific but common case when the likelihood is Gaussian (and the prior is a GP).  You start by writing down Bayes theorem, the numerator is a product of normals, and then you can integrate out the GP.  It's just a math trick whose result is something that *looks* like the GP and the likelihood are sort of the same thing.  This is the source of a lot of confusion.  I almost always see that result presented as "this is your first GP" without going through these steps, which is at best confusing, and at worst kind of not correct.  I think this is a good place to explicitly link to Bayes theorem because you need to to do the derivation. 

> The split between MVN and GP is great. To better highlight this at the start of section 30 we can copy the definition that that's mentioned in section 60, and then repeat it again in section 60.

That's a great idea, it'd be good to start with the definition. 

> No specific questions. For rest of cousre then woulld we
Lesson Kernels
Rexplain mauna loa
Practial examples and downsides? That GPs can have issues regularly and there's new advances like HSGP to deal with stuff like this?

A lot of the issues GPs have come (other than large data sets) from bad priors on the scale and lengthscale, I hope this section helps people avoid them!  

I have a rough outline in my head at this point, but I'm not sure of the ordering.  Here's what I'm thinking though.

1.  Matern kernels.  Introduce Matern family next.  ExpQuad is part of this family.  The lesson about lengthscale priors applies to the whole Matern family, not just ExpQuad (and is not relevant to kernels outside the Matern family), so I think this lesson should come next.  In this lesson I want to introduce additive models, mean functions, and multi dimensional inputs.  Have an example with real ag field data (not from a certain company, an open data set) that illustrates additive models, 2d inputs, and why the PC prior helps a lot.  It ties everything together up until this point.  

2.  Marginalization and Conditioning.  Explained marginalization above.  Then need conditioning, which is how you make predictions with GPs after you've done fitting, not done simultaneously like we did in the GP intro lesson.  Then once these concepts are introduced we can start using the GP PyMC library and stop doing everything from scatch with MvNormals.  The Mauna Loa case study ties these things together.  It could be done in this lesson or after on its own.  Would also need to introduce the periodic kernel at some point, but at this point we have everything else we need.

3.  GPs for larger data sets.  This lesson could be a bit of a survey, and doesn't have to go too deep into any particular method.  In PyMC this is HSGPs, inducing point methods, Kronecker structure.  Should also quickly show the variational inference stuff in GPFlow, GPyTorch, because they cover stuff that I think are out of scope for PyMC but still very useful.

After these two lessons you have what I'm thinking of as the "core" material.  Someone should be able to confidently useGPs in their work and make models that are actually.  What we add from here would take peoples skills to the next level.  Some ideas are:

- Deep dive into kernels.  Lots more kinds past Matern family or periodic.  Connections to other models, neural nets, AR time series models, random walks.  This one maybe should be in the core material.
- Some theory.  Feature space vs. weight space.  Connections to linear models.  Go through the main GP theorems.  Some of the stuff in https://arxiv.org/pdf/1807.02582.pdf.  Rassmussen and Williams is pretty outdated here.  Someone in the feedback mentioned wanting an introduction to this stuff.
- GPs for time series.  Like with the AR model connection, Matern GPs can be represented in a state space form.  I think this is possible in PyMC now as of pretty recently from the stuff Jesse Grabowski did but I need to actually do it and make sure.
- Gaussian random fields.  Models where the GP is "finite", like a spatial model for the 50 US states (you don't need a full GP because you're not forecasting at the 51st state).  This is stuff like CAR, ICAR, BYM models.

**Comment by canyon289** [comment]
Thanks for the really long and detailed response. For the course overall the only other section I would add is an explainer for mauna loa GP in depth. There were many comments



> I guess I'm a little confused by what you're after here. The likelihood is defined as p(data | theta) right, and there's no observed data at this point. So Bayes theorem isn't involved yet 

Ah you're right. What I'm getting at then is showing the likelihood difference between a "bad" estimation, and good one. Both in code and in pictures. The idea is to show how the samples drawn from MVNs/GPs are ranked/selected. Does this make sense and would it avoid confusion?

 An example could be like the picture below, and then paired with it show the actual numerical likelihood (like this `stats.norm(10, 1).pdf([10, -100])`). We could use PyMC logp evaluation, like the one shown below in the exception.

image

image


> Someone should be able to confidently useGPs in their work and make models that are actually. 
This is great, feels right for this audience

**Comment by bwengals** [comment]
> an explainer for mauna loa GP in depth. There were many comments

Yeah there were.  It sounded to me like people were caught off guard by that example, and felt a bit overwhelmed.  I think it would be safe to move to the planned lesson about marginalization and conditioning.

> The idea is to show how the samples drawn from MVNs/GPs are ranked/selected. Does this make sense and would it avoid confusion?

Ah ok I think I see what you're after now.  But, what's the specific gap or missing piece in building up the logic you're trying to fill?  It seems obvious that p(data = sample far from posterior | theta)p(theta) < p(data = sample from the posterior | theta) p(theta).  Or maybe I'm still missing the point... maybe you have a link to something you read that demos it this way?

**Comment by canyon289** [comment]
> p(data = sample far from posterior | theta)p(theta) < p(data = sample from the posterior | theta) p(theta).

Basically that. In the other courses its been helpful to remind folks of easy things, in case they didnt know it/forgot or to add a simple section before adding hard things again

**Comment by bwengals** [comment]
Gotcha, makes sense then.  Just wanted to make sure I understood without filling things in on my own.  I think something that breaks continuity could add confusion if placed in the wrong place though.  Where would you put it?

**Comment by canyon289** [comment]
all files copied to linked PR

**Pull request closed without merging**
