### PR TITLE
Lesson 02 section 40

### PR DESCRIPTION
**Pull request by bwengals**
The last GP part isnt done yet.  The full GP on mauna loa is pretty much from https://docs.pymc.io/en/v3/pymc-examples/examples/gaussian_processes/GP-MaunaLoa.html.  Going to use either ADVI or MAP estimate.  Will motivate approximations.

### CODE REVIEW

**Comment by bwengals** [comment]
<p>Pushed before I read this comment, model looks pretty decent now!</p>

---

 <a href='https://app.reviewnb.com/bwengals/etc/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>Good idea</p>

---

 <a href='https://app.reviewnb.com/bwengals/etc/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>oh good!  I thought it was important to emphasize too that, the lengthscale isn't really optional right.  If you try and not include it or not think about it youre actually just fixing it at one. </p>

---

 <a href='https://app.reviewnb.com/bwengals/etc/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>We probably could include some animation of this while talking.  Like, typing it in to maps and stuff.  Just for some motion?</p>

---

 <a href='https://app.reviewnb.com/bwengals/etc/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>thanks! done on purpose: https://en.wikipedia.org/wiki/Kernel_method should probably include a link</p>

---

 <a href='https://app.reviewnb.com/bwengals/etc/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>Thats a great point, I didn't think about slides while writing.  Lots of text here.  </p>

---

 <a href='https://app.reviewnb.com/bwengals/etc/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Yea good idea that would be nice</p>

---

 <a href='https://app.reviewnb.com/bwengals/etc/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request closed without merging**
